CREATE TABLE LAB3PN_AUTHORITIES
(
    USERNAME VARCHAR2(50) NOT NULL,
    AUTHORITY VARCHAR2(50) NOT NULL
);

INSERT INTO LAB3PN_AUTHORITIES(USERNAME, AUTHORITY) VALUES('nikita', 'ROLE_GUEST');
INSERT INTO LAB3PN_AUTHORITIES(USERNAME, AUTHORITY) VALUES('mark', 'ROLE_CUSTOMER');
INSERT INTO LAB3PN_AUTHORITIES(USERNAME, AUTHORITY) VALUES('nataly', 'ROLE_ADMIN');

CREATE TABLE LAB3PN_USERS
(
    USER_ID NUMBER NOT NULL,
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(68) NOT NULL,
    ENABLED NUMBER NOT NULL,
    CONSTRAINT USERS_PK PRIMARY KEY (USERNAME)
);

INSERT INTO LAB3PN_USERS(USER_ID, USERNAME, PASSWORD, ENABLED)
VALUES(1, 'nikita', '{bcrypt}$2a$10$5689VtIuGDDpg8Rc982K.OxF9MLA0lIbWriHjEaMwq33UdKM19XmS', 1);
INSERT INTO LAB3PN_USERS(USER_ID, USERNAME, PASSWORD, ENABLED)
VALUES(2, 'mark', '{bcrypt}$2a$10$/EQwbkboJM/csoA1CXzzU.YN5YGuFkf6vYjkpYkWyxwyy3Mpq3nD2', 1);
INSERT INTO LAB3PN_USERS(USER_ID, USERNAME, PASSWORD, ENABLED)
VALUES(3, 'nataly', '{bcrypt}$2a$10$ebuyTlzdC2M806mHBDRS7e6LNRMjIEu1CPARAJAzucbiGhAWd.QN2', 1);

ALTER TABLE LAB3PN_AUTHORITIES ADD CONSTRAINT AUTHORITIES_FK FOREIGN KEY (USERNAME) REFERENCES LAB3PN_USERS (USERNAME) ON DELETE CASCADE;
