-- create table users
CREATE TABLE LAB3PN_USERS
(
    CUSTOMER_ID NUMBER NOT NULL,
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(68) NOT NULL,
    AUTHORITY VARCHAR2(50) NOT NULL,
    ENABLED NUMBER NOT NULL,
    CONSTRAINT USERS_PK PRIMARY KEY (CUSTOMER_ID)
);

-- sequence for users table
CREATE SEQUENCE LAB3PN_USERS_SEQ MINVALUE 1 START WITH 5 INCREMENT BY 1 CACHE 20;

-- create plane table
CREATE TABLE LAB3PN_PLANE
(
    PLANE_ID NUMBER NOT NULL,
    PLANE_NAME VARCHAR2(50) NOT NULL,
    PLANE_TYPE VARCHAR2(20) NOT NULL,
    CONSTRAINT PLANE_PK PRIMARY KEY (PLANE_ID)
);

-- sequence for plane table
CREATE SEQUENCE LAB3PN_PLANE_SEQ MINVALUE 1 START WITH 5 INCREMENT BY 1 CACHE 20;

-- create airport table
CREATE TABLE LAB3PN_AIRPORT
(
    AIRPORT_ID NUMBER NOT NULL,
    AIRPORT_NAME VARCHAR2(70) NOT NULL UNIQUE,
    LOCATION VARCHAR2(25) NOT NULL,
    CONSTRAINT AIRPORT_PK PRIMARY KEY (AIRPORT_ID)
);

-- sequence for airport table
CREATE SEQUENCE LAB3PN_AIRPORT_SEQ MINVALUE 1 START WITH 5 INCREMENT BY 1 CACHE 20;

-- create flight table
CREATE TABLE LAB3PN_FLIGHT
(
    FLIGHT_ID NUMBER NOT NULL,
    FLIGHT_NAME VARCHAR2(25) NOT NULL,
    FLIGHT_TIME VARCHAR2(25) NOT NULL,
    PLANE_ID NUMBER NOT NULL,
    AIRPORT_ID NUMBER NOT NULL,
    CONSTRAINT FLIGHT_PK PRIMARY KEY (FLIGHT_ID),
    CONSTRAINT PLANE_FK FOREIGN KEY (PLANE_ID) REFERENCES LAB3PN_PLANE (PLANE_ID) ON DELETE CASCADE,
    CONSTRAINT AIRPORT_FK FOREIGN KEY (AIRPORT_ID) REFERENCES LAB3PN_AIRPORT (AIRPORT_ID) ON DELETE CASCADE
);

-- sequence for flight table
CREATE SEQUENCE LAB3PN_FLIGHT_SEQ MINVALUE 1 START WITH 5 INCREMENT BY 1 CACHE 20;

-- create customer order table
CREATE TABLE LAB3PN_CUSTOMER_ORDER
(
    CUSTOMER_ORDER_ID NUMBER NOT NULL,
    CUSTOMER_ID NUMBER NOT NULL,
    ORDER_TIME DATE NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    DISCOUNT DECIMAL(10, 2) NOT NULL,
    FINAL_PRICE DECIMAL(10, 2) NOT NULL,
    CONSTRAINT CUSTOMER_ORDER_PK PRIMARY KEY (CUSTOMER_ORDER_ID),
    CONSTRAINT CUSTOMER_ORDER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES LAB3PN_USERS (CUSTOMER_ID) ON DELETE CASCADE
);

-- sequence for customer order table
CREATE SEQUENCE LAB3PN_CUSTOMER_SEQ MINVALUE 1 START WITH 4 INCREMENT BY 1 CACHE 20;

-- create ticket table
CREATE TABLE LAB3PN_TICKET
(
    TICKET_ID NUMBER NOT NULL,
    SERIAL_NUMBER VARCHAR2(255) NOT NULL UNIQUE,
    FLIGHT_ID NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(255) NOT NULL,
    FLIGHT_DATE VARCHAR2(50) NOT NULL,
    ARRIVAL_DATE VARCHAR2(50) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    CONSTRAINT TICKER_ID PRIMARY KEY (TICKET_ID),
    CONSTRAINT FLIGHT_FK FOREIGN KEY (FLIGHT_ID) REFERENCES LAB3PN_FLIGHT (FLIGHT_ID) ON DELETE CASCADE
);

-- sequence for ticket table
CREATE SEQUENCE LAB3PN_TICKET_SEQ MINVALUE 1 START WITH 6 INCREMENT BY 1 CACHE 20;

-- create ordered ticket table
CREATE TABLE LAB3PN_ORDER_TICKET
(
    ORDER_ID NUMBER NOT NULL,
    CUSTOMER_ORDER_ID NUMBER NOT NULL,
    TICKET_ID NUMBER NOT NULL,
    CONSTRAINT ORDER_TICKET_PK PRIMARY KEY (ORDER_ID),
    CONSTRAINT TICKET_FK FOREIGN KEY (TICKET_ID) REFERENCES LAB3PN_TICKET (TICKET_ID),
    CONSTRAINT CUSTOMER_TICKET_FK FOREIGN KEY (CUSTOMER_ORDER_ID) REFERENCES LAB3PN_CUSTOMER_ORDER (CUSTOMER_ORDER_ID) ON DELETE CASCADE
);

-- sequence for ordered ticket table
CREATE SEQUENCE LAB3PN_ORDER_SEQ MINVALUE 1 START WITH 5 INCREMENT BY 1 CACHE 20;
