-- drop tables in the order of its creation
DROP TABLE LAB3PN_USERS;
DROP TABLE LAB3PN_PLANE;
DROP TABLE LAB3PN_AIRPORT;
DROP TABLE LAB3PN_FLIGHT;
DROP TABLE LAB3PN_CUSTOMER_ORDER;
DROP TABLE LAB3PN_TICKET;
DROP TABLE LAB3PN_ORDER_TICKET;

-- same thing for sequences
DROP SEQUENCE LAB3PN_USERS_SEQ;
DROP SEQUENCE LAB3PN_PLANE_SEQ;
DROP SEQUENCE LAB3PN_AIRPORT_SEQ;
DROP SEQUENCE LAB3PN_FLIGHT_SEQ;
DROP SEQUENCE LAB3PN_CUSTOMER_SEQ;
DROP SEQUENCE LAB3PN_TICKET_SEQ;
DROP SEQUENCE LAB3PN_ORDER_SEQ
